---
version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    network_mode: "host"
    #ports:
    #  - 9091:9091
    #  - 51413:51413
    #  - 51413:51413/udp
    restart: unless-stopped
  sonarr:
    entrypoint: ["echo", "Service sonarr disabled"]
    # restart: unless-stopped
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/tv:/tv
      - ./sonarr/downloads:/downloads
    ports:
      - 8989:8989
  radarr:
    entrypoint: ["echo", "Service radarr disabled"]
    # restart: unless-stopped
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies
      - ./radarr/downloads:/downloads
    ports:
      - 7878:7878
  jackett:
    entrypoint: ["echo", "Service jackett disabled"]
    # restart: unless-stopped
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    ports:
      - 9117:9117
  samba:
    image: dperson/samba
    container_name: samba
    command: >
        -n 
        -S
        -w "WORKGROUP"
        -s "shared;/mount;yes;no;yes;all;none;;mount"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./transmission/downloads:/mount/tm
      - /mnt/sdd/sda1:/mount/sdd
      - /mnt/sde/ttg:/mount/sde
    network_mode: "host"
    #ports:
    #  - 137:137/udp
    #  - 138:138/udp
    #  - 139:139
    #  - 445:445
    restart: unless-stopped
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    command: --max_allowed_packet=32505856
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=nas
      - MYSQL_PASSWORD=nas
      - MYSQL_DATABASE=nas
      # - MYSQL_HOST=0.0.0.0
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
  gogs:
    # entrypoint: ["echo", "Service gogs disabled"]
    restart: unless-stopped
    image: gogs/gogs
    container_name: gogs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./gogs/data:/data
    ports:
        - "7922:22"
        - "7980:3000"
  drone:
    restart: unless-stopped
    image: drone/drone:1
    container_name: drone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GOGS_SERVER=http://gogs.snail.n2n.kkito.cn
      - DRONE_RPC_SECRET=123123
      - DRONE_SERVER_HOST=drone.snail.n2n.kkito.cn
      - DRONE_SERVER_PROTO=http
    volumes:
      - ./drone/data:/data
    ports:
        - "7880:80"
        - "7843:443"
  drone-runner:
    restart: unless-stopped
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_HOST=drone.snail.n2n.kkito.cn
      - DRONE_RPC_SECRET=123123
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_RUNNER_NAME=runner.snail.n2n.kkito.cn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - "7780:3000"
  emby:
    entrypoint: ["echo", "Service emby disabled"]
    # restart: unless-stopped
    image: emby/embyserver:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./emby/config:/config
      - ./transmission/downloads/complete:/mnt/movies
      - ./emby/content:/mnt/content
    ports:
      - 8920:8920
      - 8096:8096
  aria2:
    restart: unless-stopped
    image: xujinkai/aria2-with-webui
    container_name: aria2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      # - SECRET=YOUR_SECRET_CODE
    volumes:
      - ./aria2/config:/conf
      - ./aria2/data:/data
    ports:
      - 6800:6800
      - 6880:80
      - 6888:8080
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
