---
version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/tv:/tv
      - ./sonarr/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies
      - ./radarr/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  samba:
    image: dperson/samba
    container_name: samba
    command: >
        -w "WORKGROUP"
        -s "shared;/mount;yes;no;yes;all;none;;mount"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./transmission/downloads/complete:/mount/tm
    ports:
      - 139:139
      - 445:445
    restart: unless-stopped
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=nas
      - MYSQL_PASSWORD=nas
      - MYSQL_DATABASE=nas
      # - MYSQL_HOST=0.0.0.0
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
